### ISSUE TITLE
Solar panels not working

### ISSUE THREAD

**Issue by thaurane** [Kopernicus/Kopernicus#262] opened 2018-02-03 22:27 UTC
Kopernicus is definitely the mod causing the issue. The solar panels were working fine before I installed this mod. When I try to right click them no panel is brought up and no power is being sent to the battery.

**Comment by Sigma88** [comment] 2018-02-03 22:49
hi, to help you with your issue we need some more info

if you follow the instructions [here](https://forum.kerbalspaceprogram.com/index.php?/topic/140580-0/&page=27#comment-2793409) we should be able to find where the issue is

**Comment by thaurane** [comment] 2018-02-04 04:35
Sorry for the delay in a reply I didn't expect a reply so fast. So after removing and reinstalling some mods. I can't seem to reproduce the problem. I haven't tried every possible combination (mainly because my patients is gone) of the mods I have. But they seem to be working again. If it comes up again I'll follow the instructions you provided.

**Comment by thaurane** [comment] 2018-02-04 04:58
Nvm. Its doing it again. But instead of the solar panels its rockets generating power now.

**Comment by Sigma88** [comment] 2018-02-04 12:04
kopernicus doesn't touch rockets so that cannot be kopernicus' fault

**Comment by Sigma88** [comment] 2018-02-10 23:15
are you still experiencing this issue or can we close it?

**Comment by taviLaies** [comment] 2018-03-13 01:11
I'm having the same issue with solar panels. Traced it down to this mod. 
With it my basic solar panels are not generating anything. Uninstall it, load the save and electricity is being generated.
I'm running KSP 1.4.0.2077, updated from 1.3. Started a new campaign and the first solar panels I unlocked aren't working.
I will post the log files a bit later today when I get a chance.

**Comment by Galileo88** [comment] 2018-03-13 01:19
It is impossible that you are running this mod on 1.4. Kopernicus is version locked and will not function.

**Comment by joelmeaders** [comment] 2018-03-13 02:36
Believe it or not, I also have it running on 1.4 and solar panels produce no energy.

**Comment by Galileo88** [comment] 2018-03-13 03:05
No you don't. The MM cfgs for solar systems that come with Kopernicus might be doing something, but Kopernicus does not load in 1.4.

**Comment by taviLaies** [comment] 2018-03-13 03:50
I have it Installed via CKAN. I did need to enable 1.3 compatibility. I included a screenshot of the mods.
KSP Add On Version Checker reports it as a compatibility issue at startup.
![mods](https://user-images.githubusercontent.com/16595179/37321685-6ec88848-2647-11e8-839b-fd487e477928.jpg)

I guess the config files are getting picked up as you said. I couldn't find any log files.

At least the effect of installing it is now documented.  Looking forward to it being compatible with 1.4.

**Comment by Sigma88** [comment] 2018-03-13 20:56
kopernicus is version locked, it won't load on any version other than the intended one

**Closed by Sigma88** 2018-03-13 20:56 UTC

**Comment by skikeo** [comment] 2020-01-12 04:05
Hey @Sigma88 I'm also having this issue despite Kopernicus being version locked. It seems that the solar panel model from Kopernicus is loading, but not working, in the newest version. Uninstalling Kopernicus fixed it. Excited for the new update!

**Comment by DeltaDizzy** [comment] 2020-01-12 04:25
ModuleManager strips out the stock module and replaces whether Kopernicus works or not (it has no way of knowing).

**Comment by skikeo** [comment] 2020-01-12 06:05
@DeltaDizzy Sweet, thanks for letting me know, sorry for necro then. I'll just wait for an update :)
