### ISSUE TITLE
Shadow Bug

### ISSUE THREAD

**Issue by Kopernicus-Shadows2** [Kopernicus/Kopernicus#501] opened 2021-10-26 20:08 UTC
The broken stock shadows are still persisting, even after release 59. I am on ksp version 1.12.2, and tested with no other mods installed.

**Comment by R-T-B** [comment] 2021-10-30 12:41
This does seem to be the behavior right now, yeah.

Unfortunately as your screenshots illustrate, it's still not right.  Let me see if I can't get it closer to stock with the next bugfix.  Thanks for the report.

**Comment by Kopernicus-Shadows2** [comment] 2021-10-30 13:28
If it's any help, the bug appears to be related not to the shadows themselves, but to the distance at which their quality is reduced.

**Comment by R-T-B** [comment] 2021-10-30 13:31
> 
> 
> If it's any help, the bug appears to be related not to the shadows themselves, but to the distance at which their quality is reduced.

Yes, the issue is stock calculates shadow cascades dynamically where Kopernicus uses a fixed value for various reasons.

I think I have a work around though.  I will push it pretty soon in next release.  Will update when that happens.

**Comment by R-T-B** [comment] 2021-10-30 14:06
Please see if the latest release helps or makes this acceptable:

https://github.com/Kopernicus/Kopernicus/releases/tag/release-60

**Comment by moosey-moose** [comment] 2021-11-16 04:55
I am experiencing this issue, I did not have the problem before installing Kopernicus and Kopernicus is the only addon I have installed that adds any shaders. Random shadows flicker on my craft depending on the zoom level, and the surface of Minmus has large flickering areas of shadow when moving the camera, while Kerbin seems to be fine. 

I installed Scatterer and it resolved the issue for me, just wanted to note that it still seems to be an issue.

I have a 3080Ti

**Comment by R-T-B** [comment] 2021-11-16 05:29
Interesting.  Glad I left this open, then.

You are using the latest release, correct?

If so it may still need more work yet.  Scatterer is a known work around but it'd be ideal to not require it to fix this.

**Comment by Kopernicus-Shadows2** [comment] 2022-01-23 00:59
it came back in flight and editor views even with scatterer

**Comment by R-T-B** [comment] 2022-01-23 04:30
I'm toying with some ideas on how to fix this.  It's hard, to be honest, because some old Kopernicus design decisions make shadows a bit screwy by nature.

Expect the next release to improve things though, it's on the todo list.

**Comment by R-T-B** [comment] 2022-01-29 16:32
This should now be fixed, anyone want to provide feedback on that?

**Comment by Kopernicus-Shadows2** [comment] 2022-01-30 20:23
The space center view looks great, and the editor has improved some, but the flight view has gotten worse.
![20220130152037_1](https://user-images.githubusercontent.com/93224219/151716337-c63ada02-c283-4b93-9f86-79dc9d1b9bb5.jpg)
![20220130152028_1](https://user-images.githubusercontent.com/93224219/151716340-48da2564-d084-4ebc-a5bc-b5f9dd8d5211.jpg)

**Comment by Kopernicus-Shadows2** [comment] 2022-01-30 20:24
notice the weird lines on the wing in the second screenshot

**Comment by R-T-B** [comment] 2022-01-30 22:21
Thanks for the report.  I'll continue to monitor the situation in hopes a better fix can be found.

**Comment by R-T-B** [comment] 2022-01-31 07:16
https://github.com/Kopernicus/Kopernicus/releases/tag/release-76

This release implements a new shadow manager that I hope will offer equivalent quality to stock.  Please evaluate.

**Comment by Kopernicus-Shadows2** [comment] 2022-02-09 22:19
![20220209171755_1](https://user-images.githubusercontent.com/93224219/153299779-92fc445f-abed-4d28-936c-9b94b8795a69.jpg)
the shadows are still the same

**Comment by Kopernicus-Shadows2** [comment] 2022-02-09 22:22
As a side note, I keep hearing about how scatterer is supposed to be running the shadows independently, but this doesn't seem to work for me. Is there a setting I have to enable, or something else?

**Comment by Kopernicus-Shadows2** [comment] 2022-02-10 23:40
Thanks! That worked

**Comment by R-T-B** [comment] 2022-05-28 10:10
this should be addressed in release-94, at least as best we are able.  Questions/comments welcome for a period of one week or so before I close this issue.

**Closed** 2022-06-02 23:02 UTC
Labels: bug, fixed, feedback wanted
