### ISSUE TITLE
release-192 breaks RP-1, KSC not loading

### ISSUE THREAD

**Issue by xanathos79** [Kopernicus/Kopernicus#603] opened 2023-11-13 11:26 UTC
Hi,

installing the latest release (192) breaks RP-1. After upgrading the main KSC screen remains blank and appears stuck in "loading".
Downgrading Kopernicus to the previous release fixes the issue. I have tried a full fresh install of KSP1 + RP-1 express install (which installs Kopernicus R192) and its broken there as well.
Please let me know if there is any information I can provide to help resolve this issue, cheers.

**Comment by Hunweibyn** [comment] 2023-11-13 11:41
Having this problem too after update

**Comment by Alforath** [comment] 2023-11-13 15:07
Same here :(

**Comment by xanathos79** [comment] 2023-11-13 16:06
As a workaround, downgrade the kopernicus version to the previous release. on CKAN, select Kopernicus in the list of installed mod, click on the versions tab on the right and select the second latest version and apply.
<img width="758" alt="ckan_Y3mr7qdVMy" src="https://github.com/Kopernicus/Kopernicus/assets/21085125/1f4cc22f-3409-4282-a5a1-6524cacdff71">

**Comment by R-T-B** [comment] 2023-11-13 18:24
We are working on finding the cause of this now, sorry for the inconvenience.  Reverting will indeed work as a temporary fix.

**Comment by R-T-B** [comment] 2023-11-13 23:45
FYI the Kopernicus team has figured out the issue that was making Kopernicus break on the latest update.  An additonal workaround is now available that will probably be deployed by the RP-1 team shortly, in the text file <KSPDIR>/GameData/Parallax/Config/ParallaxGlobal.cfg please set "enableScatters" to false.
Standard scatters should still work, to my knowledge the RP-1 team does not use Parallax scatters, and having it on while not using them was causing some kind of weird parallax Kopernicus joint bug that would've been very hard to see coming.  Apologies.

**Comment by xanathos79** [comment] 2023-11-14 09:33
There is absolutely no need to apologize. I appreciate the quick response and resolution of the issue as well as all the hard work put into all these fantastic mods!
I can confirm that the config changes fixes the issue and I see that some mods already picked up this fix.

**Comment by Hunweibyn** [comment] 2023-11-14 09:47
> .......... Apologies.

Thank you guys for your hard work and efforts. The way you react to problems is an example for large studios and you have nothing to apologize for!

**Comment by R-T-B** [comment] 2023-11-14 19:38
Lol it's appreciated.  Closing this as RP-1 has picked up the fix now.

**Closed by R-T-B** 2023-11-14 19:38 UTC
