### ISSUE TITLE
Landing Gear Clipping Through Terrain, Vessel Slides Across Surface, Wheels do not work

### ISSUE THREAD

**Issue by sacr3dbac0n0** [Kopernicus/Kopernicus#459] opened 2020-10-03 22:29 UTC
Issue is indiscriminate and affects many planetary bodies from different planet packs by different authors. Vessel slides on the slightest slope and is not an issue with the brakes. The motors on wheels run, but the vessel does not move nor steer from it. It happens on all stock/modded gear and wheels. I have found no ways to alleviate this, new save, fresh reinstall, stripped down gamedata to Kopernicus and planet packs only to no effect. I am on Win x64 and currently on 1.9.1-7. It happens on both 1.8.1-1 and 1.10.1 bleeding edge I can confirm.

Let me know If you need any more information, I can easily reproduce this 100% of the time.

A video of a more extreme scenario: https://www.youtube.com/watch?v=KOVDijVEDf8&feature=youtu.be
![unknown](https://user-images.githubusercontent.com/69779657/95002819-22f5e500-058d-11eb-904a-b7f8b3be9ff2.png)

**Comment by R-T-B** [comment] 2020-10-04 00:59
Interesting.  I'm surprised this hasn't been reported yet.  I can only assume most of our players must be building VAB craft.  A major bug all the same, we will put this at the top of our priority list.  You said it happens in the old 1.8 build as well?

Looking into it now, hope to have an update soon.

**Comment by R-T-B** [comment] 2020-10-04 01:18
As help in diagnostics, is there any body you can identify where this does not occur?

**Comment by sacr3dbac0n0** [comment] 2020-10-04 01:42
I can not find a body in which the terrain consistently works. I've been to all planets in GU, Low Light Levels Blue, and Red, and Blinding Light Levels and the terrain is all non-functional. I've noticed that saves tend to degrade in terms of terrain functionality, when starting a new save the terrain seems to work for a couple of hours, but breaks down until it gets worse and worse. I cannot seem to easily reproduce this on the Beyond Home inner system though. 

I feel that factors in this issue are the distance from the home system and save game age because I remember last I visited GU (a while ago) the terrain was more functional, certainly more than it is now. GU is pretty close to the home system.

I'll work on that savegame for you probably tomorrow. I'll have it set up on 1.9.1 so that you only need the planet packs I've mentioned (GU, B2L, 3LR, and 3LB), excluding Beyond Home

**Comment by R-T-B** [comment] 2020-10-04 03:43
It sounds like if it's distance related, it could be out of our hands.  We could be dealing with Unity floating point math errors from the sheer distance of some of these planet packs from point "zero" (the home sun).  That would be unfortunate, but also completely unfixable since we can't exactly switch game engines.  Let's hope not.  Awaiting that save game.

**Comment by sacr3dbac0n0** [comment] 2020-10-04 04:43
Check this out, If you want to try out other planets just use the "Rocket-powed VTOL" craft, it has wheels on it so you can rove around. All of the rovers I placed in the tracking station should show the issue, either that or explode from the terrain for no reason.

[Michael 1_8_1 Sandbox test.zip](https://github.com/Kopernicus/Kopernicus/files/5322667/Michael.1_8_1.Sandbox.test.zip)

**Comment by R-T-B** [comment] 2020-10-04 06:18
Thanks, can replicate.  Will look at fixing this, if possible.  I will poke at the savegame more tomorrow to see if I can't find exactly what causes this...  I would now, but it's 11pm here, and all coders must sleep sometime.

Hope we can get this fixed soon though.  It seems this bug has existed for a while.

**Comment by sacr3dbac0n0** [comment] 2020-10-05 18:27
Log, as requested:
[KSP.log](https://github.com/Kopernicus/Kopernicus/files/5329363/KSP.log)

**Comment by psamathe2000** [comment] 2020-10-06 20:17
Hi I thought it might be helpful to mention that I have seen this issue in the OPM planet pack (i.e. a non interstellar pack). I had a rover on the outermost planet (Plock) which was unable to move and had its wheels clipped through the surface like that first picture above. Last time I looked at it (couple of days ago) it seemed to have stopped doing it. 

I know I've also seen it on other OPM moons (Urlum or Sarnus) but I can't remember which one.

**Comment by sacr3dbac0n0** [comment] 2020-10-07 03:44
Yup, that's the exact problem. It seems to vary in severity depending on how far away the body is from the universe center (Kerbol). Unfortunately, it seems that this issue is out of our hands and is left to Squad to deal with. I've made a bugtracker issue about a month ago, but I don't have any hopes that Squad will look at this.

**Comment by R-T-B** [comment] 2020-11-06 17:58
We have reports this may be related to day/night cycle of the planet in some way.  Further investigation is warranted.

**Comment by R-T-B** [comment] 2020-12-20 01:44
This issue has been traced back to ModularFlightIntegrator code.  An experimental patch was issued using a fork of MFI, in Release 56 of BE and 16 of stable, please test.

**Comment by pckbls** [comment] 2021-01-04 03:45
Hi there,

I am also affected by this bug using the Beyond Home Planet Pack backed by the KSP 1.10.1 version of https://github.com/R-T-B/Kopernicus/releases/tag/UBE-release-58

I've did a bunch of researched and stumbled across this particular forum post which suggests to delete the KSP expansions: https://forum.kerbalspaceprogram.com/index.php?/topic/196355-landing-gear-clipping-through-terrain-vessel-slides-across-surface/&do=findComment&comment=3851157

**I have temporarily deleted my SquadExpansions directory (which contains both the Breaking Ground and Making History expansions) and can confirm that now my landing legs are behaving properly on the "broken" celestial body.**

In my particular case this bug prevents me from using surface harvesters. The problem is shown in my little YouTube video here: https://www.youtube.com/watch?v=LpXp4PQk6Kc

Kind regards
Patrick

**Comment by R-T-B** [comment] 2021-01-04 04:07
Sadly, that further supports the idea it's a stock bug.  How did the recent MFI patches change this bugs behavior for you?  Or not at all?

**Comment by pckbls** [comment] 2021-01-04 08:55
Hi there,

where can I obtain said "MFI patch"? Do I simply have to downgrade to UBE 56? (Currently running 58).

When my work shift is over I'd like to further narrow down the reason of this issue, thus try to figure out whether it's Breaking Ground's or Making Histories' fault.

Kind regards
Patrick

**Comment by pckbls** [comment] 2021-01-04 11:53
Update: It's the Making History Expansion's fault. Running either Stock KSP or Stock KSP with Breaking Ground works fine.

**Comment by pckbls** [comment] 2021-01-04 17:00
I've just tested the ModularFlightIntegrator DLL linked in this particular post: https://github.com/sarbian/ModularFlightIntegrator/pull/12#issuecomment-748616579

Unfortunately this doesn't fix the issue for me.

**Comment by R-T-B** [comment] 2021-01-04 18:02
Apologies, yes, you tested correctly.  My lack of attentiveness lately is due to a holiday influx at my workplace requiring my constant attention.

I appreciate your research on this.  It seems MFI may not be to blame afterall.  We may want to revert our fork from them.

**Comment by pckbls** [comment] 2021-01-04 21:14
No worries. :)

I've dug a little deeper and finally managed to get it working without having to remove the Making History expansion. I've read somewhere on Reddit that back in the days way before I started to play KSP people were discouraged to use the "Low" Terrain Quality Option as this could lead to those kind of problems. The developer of Beyond Home also constantly reminds people that they *must* use the High Terrain Quality option. Unfortunately that option doesn't really do anything change anything. At least when using Beyond Home or probably any other planet pack, too.

Let's peek into into my freshly generated KSP's `settings.cfg` after the first time starting up KSP after having installed all mods:
```
TERRAIN
{
	preset = High
	version = 1.10.1
	PRESET
	{
		name = Low
		PLANET
		{
			name = Kerbin
			minDistance = 4
			minSubdivision = 1
			maxSubdivision = 8
		}
		PLANET
		{
			name = KerbinOcean
			minDistance = 4
			minSubdivision = 1
			maxSubdivision = 7
		}
		// [...]
		PLANET
		{
			name = Eve
			minDistance = 8
			minSubdivision = 1
			maxSubdivision = 10
		}
		// [...]
	}
	PRESET
	{
		name = Default
		// [...]
	}
	PRESET
	{
		name = High
		// [...]
	}
}
```

Unfortunately the auto-generated settings **only configure the stock celestial bodies**, not the ones provided by Beyond Home. Then I've added a custom section for `Voss` to the `High` preset like so:
```diff
--- settings.cfg        2021-01-04 22:05:13.607119600 +0100
+++ settings.cfg.orig   2021-01-04 22:04:52.534614300 +0100
@@ -2305,5 +2305,12 @@
                        minSubdivision = 1
                        maxSubdivision = 9
                }
+               PLANET
+               {
+                       name = Voss
+                       minDistance = 4
+                       minSubdivision = 1
+                       maxSubdivision = 6
+               }
        }
 }
```

Next up I've played around a bit with the values of `minDistance`/`minSubdivision`/`maxSubdivision` while on Voss to ensure that the game actually respects those settings. When configured wrong, the game might crash or the Vessel might disappear into the ground. Great.

Eventually I've found out that when setting `maxSubdivision` too high (e.g. `8` or `10`) the said bug occurrs. A value of `6` seems to be just fine. Both the landing legs and my surface harvester work. Proof:

![screenshot1365](https://user-images.githubusercontent.com/13433567/103579859-6851e780-4ed9-11eb-819a-b1f372171e2f.png)

Here's some explanation what the different configuration parameters are responsible for: https://wiki.kerbalspaceprogram.com/wiki/Talk:Settings

I guess I've just discovered a workaround but the real "bug" is still hidden somewhere. I'm also not really sure why the Making History Expansion also seems to be involved here... Question: Is there anything on the Kopernicus side that you can do? Otherwise I might share my insights with the Beyond Home developer and other users in the corresponding KSP forum thread.

Kind regards
Patrick

**Comment by R-T-B** [comment] 2021-01-05 03:21
Interesting...  so it's not caused by anything more or less than insufficient subdivision count, I'd wager.

I could fix it Kopernicus side, but I'd need numbers on what's appropriate to enforce relative to planet size, distance, and whatever else causes this bug.  I'd need hard math.  I know Parallax already has a way of overriding subdivision count, but I am unsure if Linx may have more insight or not.

I will be removing the MFI fork next release though, most certainly.  It seems it was completely unnecessary.

**Comment by pckbls** [comment] 2021-01-05 06:28
I'm not sure how KSP auto-generates the default quality preset values. Are they using some clever logic or has some developer at squad just hard-coded sane values? If the latter is the case, wouldn't it make sense that Planet Pack authors also have to provide working quality preset values for their planets? If technically possible, Kopernicus could inject those presets into the engine then. Otherwise planet pack user's would have to mess around with their settings.cfg like I did. Feasible but a bit too complicated for my taste.

**Comment by R-T-B** [comment] 2021-01-12 22:51
been out for a bit with a cold, here are my thoughts:

If I could prove this was related to body size (in particular difference from a template), I could have Kopernicus autoadjust for it codeside based on the planets new radius difference vs the template.  But I'm not sure that's the culprit...  anyone want to test?  What's the template of some of those bodies you played with?  How different is the radius declared from the template?

**Comment by R-T-B** [comment] 2021-01-26 02:28
This should be fixed in latest bleeding edge builds, as much as we are able without squads help anyhow.  Please test and report if it is ready for mainlining.

**Comment by pckbls** [comment] 2021-01-26 08:18
Hi there,

great news!

I've abandoned the MH expansion from my KSP installation and I haven't noticed the particular bug ever since. However I've made a backup of the "corrupted" KSP with MH installed. When I'm done working today, I'll verify whether the Kopernicus update would solve the problem.

Best
regards

**Comment by R-T-B** [comment] 2021-01-26 21:22
Interesting.  You haven't seen the bug at all in your new install?  Anything different there?

**Comment by pckbls** [comment] 2021-01-26 21:35
"New install" simply means: Use the existing installation but get rid of Making History expansion. When I've found out that RestockPlus provides parts that act as MH drop in replacements I had simply no reason to keep the expansion installed. I'm currently restoring my "broken setup". Which Kopernicus build do you want me to test? I assume the latest one? https://github.com/R-T-B/Kopernicus/releases/tag/UBE-release-67

**Comment by R-T-B** [comment] 2021-01-26 21:48
Latest is great, it has some performance optimizations to the fix.  If it fails for some reason though, try the more expensive (performance wise) fix found in release 64, just for testing.  If it works, no reason to do that.

**Comment by pckbls** [comment] 2021-01-26 22:02
Well good news: I was able to reproduce the issue with my backed up "broken" installation.

![screenshot1952](https://user-images.githubusercontent.com/13433567/105911054-098c1380-602a-11eb-8bea-efc2c43f5edf.png)

Even better news: After installing above mentioned Kopernicus release, the Vessel finally stands on its legs. 😃 

![screenshot1953](https://user-images.githubusercontent.com/13433567/105911062-0c870400-602a-11eb-9313-28413d892ff7.png)

Cudos to you! I highly appreciate your work! I will now revert back to my current installation (the one without MH) and also upgrade my Kopernicus there!

@sacr3dbac0n0 since you've opened up this Issue, could you also verify whether the most-recent Kopernicus build would solve your problems?

**Comment by R-T-B** [comment] 2021-01-27 00:11
Hooray!

I'm leaving this bug open to monitor instances of it still happening (they are rare, but I have heard of a few), but mostly, it seems to be working and when it glitches, a reload generally fixes it.  Very happy with the result.

**Comment by sacr3dbac0n0** [comment] 2021-01-28 01:29
I'm happy to say that the most recent Kopernicus build has indeed solved
this problem.

**Comment by R-T-B** [comment] 2021-01-28 02:30
All very good.

Leaving this open for an observation period just in case, but I think we can all agree this should get pushed to stable ASAP.  Even if it ends up having occasional rare issues (worst case situation IMO), it is way better than before, and there is no reason to hold this back from the stable branch any longer.

Working on it now.

**Comment by R-T-B** [comment] 2021-02-03 01:23
Closing issue for now as seems fixed.  Would reopen though if there is evidence of it still being an issue, just comment.

**Comment by R-T-B** [comment] 2021-11-19 09:47
reopening this as this issue still crops up.on edge cases.

**Comment by R-T-B** [comment] 2021-11-20 04:49
This should now be fixed via the novel method we pioneered in https://github.com/Kopernicus/Kopernicus/releases/tag/release-61

**Comment by R-T-B** [comment] 2022-02-07 08:33
This is very much not fixed, so reopening.

**Comment by R-T-B** [comment] 2022-02-10 03:01
The new update, release-79, should address this pretty well when combined with the workaround cfg, AddWatchdog.cfg.

Unfortunately some mods will need to be updated...  and Principia will not work outright.  Still looking for a better approach than spawning a fake invisible celestial nearly right on top of the landing site... (why does that work anyways?)

**Comment by R-T-B** [comment] 2022-02-20 18:34
It seems we are doing well, but the core issue is still there and this watchdog fix is janky as heck, so I am leaving this open until we can diagnose the real origin causes.

**Comment by R-T-B** [comment] 2022-06-03 23:10
The watchdog is finally dead, so closing this.

**Closed by R-T-B** 2022-06-03 23:10 UTC
Labels: bug, workaround

**Comment by Mjrlun** [comment] 2025-05-24 00:19
Hello, I have noticed this issue having become especially prevalent again (at least when using Sigma Dimensions). I don't know necessarily which of the two's fault it is, but I originally made the bug report under Sigma Dimensions: https://github.com/R-T-B/Sigma-Dimensions/issues/4
