### ISSUE TITLE
Any mod adding a star system results in exception on invocation (related to reference body)

### ISSUE THREAD

**Issue by azraelzephyrian** [Kopernicus/Kopernicus#384] opened 2019-09-14 10:27 UTC
I've tried every mod compatible with 1.7.3 that adds a new star system (AFAIK).  All of them throw the same exception.  I tried fiddling with the configs, to no avail.  I haven't uninstalled everything, but I have uninstalled everything tangentially related to kopernicus or orbital mechanics.  

[kopernicus logs .zip](url)

**Comment by Sigma88** [comment] 2019-09-14 11:12
Have you tried GN?
It used to work with kopernicus 1.7.3-1

**Comment by azraelzephyrian** [comment] 2019-09-14 11:15
> Have you tried GN?
> It used to work with kopernicus 1.7.3-1

I'll try it!

**Comment by Sigma88** [comment] 2019-09-14 11:43
www.github.com/Sigma88/Galactic-Neighborhood

**Comment by azraelzephyrian** [comment] 2019-09-14 11:53
Brilliant.  It works.

Also, thank you so much for the work you do. You're a hero :P

**Comment by azraelzephyrian** [comment] 2019-09-14 12:01
Ah.  Kerbin's terrain flickers around the VAB and OPM is totally gone.  I take it back, it's not working.  I'm gonna troubleshoot a bit.

**Comment by Sigma88** [comment] 2019-09-15 09:51
KSC terrain flicker is a result of reparenting kerbin. That is a bug we  couldnt figure out how to fix

OPM is not gone, GN moves the mod to its own star (Helios iirc)

If GN works it means that the issues you were having with star mods were caused by the mods, not kopernicus

**Comment by azraelzephyrian** [comment] 2019-09-15 09:53
Ahh ok thanks for the explanation.  I noticed another star system, I just couldn't select it in the VAB.  Maybe it's because of research bodies!  MUST reinstall.  Very interested to see how this goes.

**Comment by Sigma88** [comment] 2019-09-15 15:11
not sure if researchbodies is compatible with GN to be honest, nobody ever contacted me asking about that

**Comment by Sigma88** [comment] 2019-10-12 22:19
since this seems to be resolved I'm closing this

**Closed by Sigma88** 2019-10-12 22:19 UTC
