### ISSUE TITLE
Kopernicus not work in Ksp 1.7.1 :/

### ISSUE THREAD

**Issue by 11SHEMY11** [Kopernicus/Kopernicus#360] opened 2019-06-07 09:59 UTC
I start KSP and it is written that Kopernicus does not work on this version

**Comment by VedaantAchuthan** [comment] 2019-06-07 10:17
Kopernicus is version locked.It will only work for a specific version of ksp. It's being updated soon, don't ask when.if you want to continue playing on your save, then either downgrade your ksp version to 1.7.0 or wait.

**Comment by 11SHEMY11** [comment] 2019-06-07 13:17
Ok thanks

пт, 7 июн. 2019 г., 1:18 ПП VedaantAchuthan <notifications@github.com>:

**Comment by pmborg** [comment] 2019-06-07 15:40
Hello StollD,

I already installed this version in KSP 1.7.1 and I still get the same error as before.

[EXC 16:34:43.122] TypeLoadException: Could not load type 'System.Runtime.CompilerServices.ExtensionAttribute' from assembly 'KatLib'.
	System.MonoCustomAttrs.GetCustomAttributesBase (ICustomAttributeProvider obj, System.Type attributeType)
	System.MonoCustomAttrs.GetCustomAttributes (ICustomAttributeProvider obj, System.Type attributeType, Boolean inherit)
	System.Reflection.Assembly.GetCustomAttributes (System.Type attributeType, Boolean inherit)
	Kopernicus.RuntimeUtility.LogAggregatorWorker.Awake ()
	UnityEngine.GameObject:AddComponent(Type)
	AddonLoader:StartAddon(LoadedAssembly, Type, KSPAddon, Startup)
	AddonLoader:StartAddons(Startup)
	<LoadObjects>c__Iterator1:MoveNext()
	UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
	<CreateDatabase>c__Iterator0:MoveNext()
	UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
	GameDatabase:StartLoad()
	<LoadSystems>c__Iterator0:MoveNext()
	UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
	LoadingScreen:Start()

Please let me know how can I be more helpful.
Thanks!

**Comment by DukeSiet** [comment] 2019-06-07 15:56
Also getting similar results

**Comment by pmborg** [comment] 2019-06-07 16:09
[1] The problem of that I had that hanged at the loading screen with KSP 1.7.1 with Kopernicus-1.7.1-2.zip was solved when I removed Trajectories plugin

[2] Now I have a new one :Kerbal Space Program\Logs\Kopernicus\Kopernicus.log:
//===============================================================================================================//
//=====  Kopernicus 1.7.1-2 - (BuildDate: 07.06.2019 15:44:05; AssemblyHash: kwk9dcY553Zn86/4jdo/UpLpnF8=)  =====//
//===============================================================================================================//
[LOG 17:06:17]: Logger "Kopernicus" was created
[LOG 17:06:17]: Injector.Awake(): Begin
[LOG 17:06:17]: Parsing Target name in (Kopernicus.Configuration.Loader) as (System.String)
[LOG 17:06:17]: Parsing Target timeScale in (Kopernicus.Configuration.Loader) as (Kopernicus.ConfigParser.BuiltinTypeParsers.NumericParser`1[System.Double])
[LOG 17:06:17]: Parsing Target scale in (Kopernicus.Configuration.Loader) as (Kopernicus.ConfigParser.BuiltinTypeParsers.NumericParser`1[System.Double])
[LOG 17:06:17]: Parsing Target Epoch in (Kopernicus.Configuration.Loader) as (Kopernicus.ConfigParser.BuiltinTypeParsers.NumericParser`1[System.Double])
[LOG 17:06:17]: Parsing Target useOnDemand in (Kopernicus.Configuration.Loader) as (Kopernicus.ConfigParser.BuiltinTypeParsers.NumericParser`1[System.Boolean])
[LOG 17:06:17]: Parsing Target useOnDemandBiomes in (Kopernicus.Configuration.Loader) as (Kopernicus.ConfigParser.BuiltinTypeParsers.NumericParser`1[System.Boolean])
[LOG 17:06:17]: Parsing Target onDemandLoadOnMissing in (Kopernicus.Configuration.Loader) as (Kopernicus.ConfigParser.BuiltinTypeParsers.NumericParser`1[System.Boolean])
[LOG 17:06:17]: Parsing Target onDemandLogOnMissing in (Kopernicus.Configuration.Loader) as (Kopernicus.ConfigParser.BuiltinTypeParsers.NumericParser`1[System.Boolean])
[LOG 17:06:17]: Parsing Target onDemandUnloadDelay in (Kopernicus.Configuration.Loader) as (Kopernicus.ConfigParser.BuiltinTypeParsers.NumericParser`1[System.Int32])
[LOG 17:06:17]: Parsing Target useManualMemoryManagement in (Kopernicus.Configuration.Loader) as (Kopernicus.ConfigParser.BuiltinTypeParsers.NumericParser`1[System.Boolean])
[LOG 17:06:17]: Parsing Target mainMenuBody in (Kopernicus.Configuration.Loader) as (System.String)
[LOG 17:06:17]: Parsing Target maxViewingDistance in (Kopernicus.Configuration.Loader) as (Kopernicus.ConfigParser.BuiltinTypeParsers.NumericParser`1[System.Double])
[LOG 17:06:17]: Parsing Target scaledSpaceFaderMult in (Kopernicus.Configuration.Loader) as (Kopernicus.ConfigParser.BuiltinTypeParsers.NumericParser`1[System.Double])
[LOG 17:06:17]: Parsing Target force3DOrbits in (Kopernicus.Configuration.Loader) as (Kopernicus.ConfigParser.BuiltinTypeParsers.NumericParser`1[System.Boolean])
[LOG 17:06:17]: Parsing Target self in (Kopernicus.Configuration.Loader) as (System.Collections.Generic.List`1[Kopernicus.ConfigParser.BuiltinTypeParsers.StringCollectionParser])
[LOG 17:06:17]: [Kopernicus]: Configuration.Loader: Loaded Body: Sun
[LOG 17:06:17]: [Kopernicus]: Configuration.Loader: Loaded Body: Moho
[LOG 17:06:17]: [Kopernicus]: Configuration.Loader: Loaded Body: Eve
[LOG 17:06:17]: [Kopernicus]: Configuration.Loader: Loaded Body: Gilly
[LOG 17:06:17]: [Kopernicus]: Configuration.Loader: Failed to load Body: Squad/Kerbin: Exception has been thrown by the target of an invocation.
[LOG 17:06:26]: [Kopernicus] RuntimeUtility Started
[LOG 17:06:26]: StarLightSwitcher.Awake(): Begin

**Comment by pmborg** [comment] 2019-06-07 16:12
The detail error I believe that is here:Kerbal Space Program\Logs\Kopernicus\Squad\Kerbin.Body.log

[LOG 17:06:17]: Exception Was Recorded: Exception has been thrown by the target of an invocation.
  at System.Reflection.MonoCMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <filename unknown>:0 
  at System.Reflection.MonoCMethod.Invoke (BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <filename unknown>:0 
  at System.Reflection.ConstructorInfo.Invoke (System.Object[] parameters) [0x00000] in <filename unknown>:0 
  at System.Activator.CreateInstance (System.Type type, Boolean nonPublic) [0x00000] in <filename unknown>:0 
  at System.Activator.CreateInstance (System.Type type) [0x00000] in <filename unknown>:0 
  at Kopernicus.ConfigParser.Parser.LoadObjectMemberFromConfigurationNode (System.Reflection.MemberInfo member, System.Object o, .ConfigNode node, System.String configName, Boolean getChildren) [0x00000] in <filename unknown>:0 
  at Kopernicus.ConfigParser.Parser.LoadObjectFromConfigurationNode (System.Object o, .ConfigNode node, System.String configName, Boolean getChildren) [0x00000] in <filename unknown>:0 
  at Kopernicus.Configuration.Loader.Kopernicus.ConfigParser.Interfaces.IParserEventSubscriber.PostApply (.ConfigNode node) [0x00000] in <filename unknown>:0 
[LOG 17:06:17]: Inner Exception Was Recorded: Object reference not set to an instance of an object
  at Kopernicus.Configuration.ModLoader.LandControl+LandClassScatterLoader..ctor (.LandClassScatter value) [0x00000] in <filename unknown>:0 
  at Kopernicus.Configuration.ModLoader.LandControl.Create (.PQSLandControl mod, .PQS pqsVersion) [0x00000] in <filename unknown>:0 
  at Kopernicus.Configuration.ModLoader.ModLoader`1[T].Kopernicus.Configuration.ModLoader.IModLoader.Create (.PQSMod mod, .PQS pqsVersion) [0x00000] in <filename unknown>:0 
  at Kopernicus.Configuration.PQSLoader..ctor () [0x00000] in <filename unknown>:0 
  at (wrapper managed-to-native) System.Reflection.MonoCMethod:InternalInvoke (object,object[],System.Exception&)
  at System.Reflection.MonoCMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <filename unknown>:0

**Comment by pmborg** [comment] 2019-06-07 18:35
The problem is solved in Kopernicus 1.7.1-4
Thanks for the Quick-fix in the name, I am sure, of all Kopernicus fans :)

**Comment by PressFToPayRespekk** [comment] 2019-06-08 09:38
[KSP.log](https://github.com/Kopernicus/Kopernicus/files/3268385/KSP.log)
[Kopernicus.Runtime.log](https://github.com/Kopernicus/Kopernicus/files/3268386/Kopernicus.Runtime.log)
[Kopernicus.log](https://github.com/Kopernicus/Kopernicus/files/3268387/Kopernicus.log)
[MMPatch.log](https://github.com/Kopernicus/Kopernicus/files/3268388/MMPatch.log)
[ModuleManager.log](https://github.com/Kopernicus/Kopernicus/files/3268389/ModuleManager.log)


pls halp idk what to do halp pls 1.7.1 press f to pay respekk

**Comment by PepeLeffue** [comment] 2019-06-13 21:47
1.7.2 broke it again.  They are patching faster than mods can keep up.

**Comment by Galileo88** [comment] 2019-06-14 01:14
People still haven’t figured out how to make a separate copy of KSP outside of their steam folder? Hard to have sympathy for anyone that has this issue when it’s so simple to avoid auto updates.

**Comment by hblomqvist** [comment] 2019-06-14 03:23
You can also just go to KSP > Properties > Betas in steam and downgrade or lock the game to a version.

**Comment by PressFToPayRespekk** [comment] 2019-06-14 09:04
I mean that i have the 1.7.1 version of kopernicus and ksp and it says that a custom planet thing wont work even if i dont have any installed. and i dont havw my auto install on.

**Comment by MrXLR8** [comment] 2019-06-16 07:43
Do those small patches really break kopernicus? Maybe we can just modify version check part to get it working?

**Comment by DeltaDizzy** [comment] 2019-06-16 07:49
Kopernicus intentionally disables when the version of KSP isnt the same as the one it was compiled for. If you want to know why, [an explanation was provided a while back](https://github.com/Kopernicus/Kopernicus/issues/299#issuecomment-406890108).

**Comment by MrXLR8** [comment] 2019-06-16 08:15
I still want to risk try to launch without lock, how do I do that?

**Comment by DeltaDizzy** [comment] 2019-06-16 08:20
You have to modify and recompile Kopernicus. I won't tell you how to do that, as doing so kind of defeats the point of the version lock.

**Comment by JustynAus** [comment] 2019-06-16 11:08
Thank you to all the people responsible for making Kopernicus work.
It must be time consuming, and frustrating, when KSP releases updates in such rapid succession!

Please know that your work is appreciated, and that a silent mass of players are happy to wait for each release. You may not hear from us often, but we are out there.

**Comment by KindyKerbal987** [comment] 2019-06-24 14:05
The same issue is with KSP 1.7.2

**Comment by VedaantAchuthan** [comment] 2019-06-24 14:06
Kopernicus hasn't updated to 1.7.2, you need to use 1.7.1-5

You probably won't get a newer version anytime soon. Give it time.

**Comment by JustynAus** [comment] 2019-06-25 00:58
Word on the street is that KSP 1.7.3 will be released soon.
I'd just chill, let our man have a break, and wait for that.

**Comment by KindyKerbal987** [comment] 2019-06-25 15:47
So despite the warning it tells me nothing will happen to my saves if I use 1.7.1-5 on 1.7.2?

**Comment by VedaantAchuthan** [comment] 2019-06-25 15:51
Well Kopernicus will actively disable itself if the wrong version is loaded so the planets won't load at all. IF you can remove the version lock yourself it may load without any problems but you immediately void the warranty.

**Comment by Sigma88** [comment] 2019-06-25 19:29
@kindykerbal987 kopernicus won't work on 1.7.2

If you need to play with kopernicus I would suggest sticking with 1.7.1 for the moment

**Comment by pmborg** [comment] 2019-06-27 21:46
or just edit file:
(...) Kerbal Space Program\GameData\Kopernicus\Plugins\Kopernicus.version

update to:
(...)
	"VERSION":
	{
		"MAJOR": 1,
		"MINOR": 7,
		"PATCH": 1,
		"BUILD": 5
	},
	"KSP_VERSION":
	{
		"MAJOR": 1,
		"MINOR": 7,
		"PATCH": 2
	}
}

Is working perfectly!

**Comment by pmborg** [comment] 2019-06-27 21:58
or just check-out source code version of day 15/june and update file:
Kopernicus-release-1.7.1-5\src\Kopernicus\Constants\CompatibilityChecker.cs

Update Line 50 to:
        // Compatible version
        internal const Int32 VERSION_MAJOR = 1;
        internal const Int32 VERSION_MINOR = 7;
        internal const Int32 REVISION = 2;
        internal const Int32 KOPERNICUS = 5;

Compile: "BUILD" on Visual Studio 2017 and that's it!

**Comment by Galileo88** [comment] 2019-06-27 23:16
@pmborg hope you are willing to provide support when other come here with bugs using you instructions.

**Comment by Monniasza** [comment] 2019-09-11 17:53
It doesn't work in 1.7.3

**Comment by JustynAus** [comment] 2019-09-12 06:55
> It doesn't work in 1.7.3

https://github.com/Kopernicus/Kopernicus/releases/tag/release-1.7.3-1

Works just fine in 1.7.3

You need to use the exact version for your game.

**Comment by Monniasza** [comment] 2019-09-14 08:24
> > It doesn't work in 1.7.3
> 
> https://github.com/Kopernicus/Kopernicus/releases/tag/release-1.7.3-1
> 
> Works just fine in 1.7.3
> 
> You need to use the exact version for your game.

I do not have this exact version, please fix.

**Comment by StollD** [comment] 2019-09-14 11:26
> > > It doesn't work in 1.7.3

*link to Kopernicus for 1.7.3 is posted*

> I do not have this exact version, please fix.

Ah ok, so the mod needs fixing because you don't want to download it's latest version? It's not like it's a gigabyte to download, it's less than a megabyte.

**Closed by StollD** 2019-09-14 11:26 UTC
