### ISSUE TITLE
1.8.1-1 Terrain tiles missing

### ISSUE THREAD

**Issue by gordonfpanam** [Kopernicus/Kopernicus#424] opened 2020-02-24 02:32 UTC
Looks like a repeat of #280 occurring on 1.8.1-1. Occurring on Eve and Laythe for certain, haven't messed with Kerbin. May be related to issue discovered on JNSQ Moho but not certain.

![Kopernicus 1 8 1 terrain tiles missing 2](https://user-images.githubusercontent.com/25485283/75125479-e79c4b00-567a-11ea-81fd-bcded6e75f63.png)

KSP GameData folder has only Squad, DLC, and Kopernicus and dependencies:

![Kopernicus 1 8 1 terrain tiles missing 3](https://user-images.githubusercontent.com/25485283/75125489-ee2ac280-567a-11ea-8c29-6b10b972e9a2.png)

Yes, BUILTIN\Users has Modify access to this folder, because I know someone will ask.

**Comment by Sigma88** [comment] 2020-02-24 10:48
Did you try reproduce the same situation in stock? I doubt this behaviour would be due to sone kopernicus bug.

My best guesses would be:
1- this happens as a result of cheating a craft in orbit from another SOI (should be fixed by saving and reloading)
2- this happens as a result of some parameter that is set to a different value compared to stock (eg. PQS subdivisions) (should be fixed by a change in the planet pack you used, assuming you used one)
3- this happens on stock ksp even without kopernicus (there is no real fix there)

From the screenshot of your install folder it would seem you don't have any planet pack installed, which would mean it's more likely to be 1 or 3 rather than 2.

If you can exclude all 3 of the previous options it might actually be a kopernicus issue and I will look into it.

Another test you might try is to disable OnDemand to see if that has any effect.

```
@Kopernicus
{
    useOnDemand = false
}
```

**Comment by gordonfpanam** [comment] 2020-02-25 00:57
Did the save and reload while in Laythe flight - no change there. Exited the game, restarted, loaded the quicksave taken from Laythe flight, no change there either. Adding useOnDemand = False, no change there either.

Finally removing Kopernicus 1.8.1-1 restored the missing terrain tiles.

Easy enough to reproduce: Start stock game with this save, load the Quicksave, and observe Laythe's terrain directly above the Aeris 4a in flight. 

[Bloody Hell.zip](https://github.com/Kopernicus/Kopernicus/files/4247559/Bloody.Hell.zip)

**Comment by Sigma88** [comment] 2020-02-25 01:08
great, thanks for the bug report

I will look into this as soon as I get some free time

**Comment by Sigma88** [comment] 2020-02-25 16:48
I tested the save you sent me on 1.9.0 and the issue is not happening

I will test on 1.8.1 as well, just in case.

in the meantime, could you send me your `settings.cfg` file (found in the KSP install folder) to check if you have some weird setting that might be affecting your game (because I don't think just updating to 1.9.0 will fix this)

also, if you are on the discord server ping me and I will send you a dev version for 1.9.0 so you can test there if you want

**Comment by Sigma88** [comment] 2020-02-25 16:56
I tested on 1.8.1 as well, with the latest kopernicus release and your save game. No issues for me.

it might be linked to some settings you have that are different from my settings.

I doubt it could be a performance issue because I am testing this on my extremely-potato-laptop and I don't have issues

**Comment by gordonfpanam** [comment] 2020-02-26 01:27
I do have an NVidia GTX 1080 card in my 2014-vintage PC and I recently updated its drivers... I'll be back with logs shortly.

**Comment by Sigma88** [comment] 2020-02-26 08:31
> I do have an NVidia GTX 1080 card in my 2014-vintage PC and I recently updated its drivers... I'll be back with logs shortly.

I don't think this is a graphics issue, I think generally speaking ksp is more taxing on the CPU rather than the GPU

> Thinking about my video card driver issue, I went back to that JNSQ 0.8.6 / KSP 1.7.1 save I have on Eve where I found missing tiles on 1.8.1, and they weren't missing there.

did you make a comparison between those settings and your current settings?

> One thing I noticed: When I loaded the save, the missing terrain was there at first, and then seconds later it disappeared. Does something cull possibly-unneeded terrain to save on memory?

not that I know of, I would say if there is anything doing that it is not on the kopernicus side

**Comment by Sigma88** [comment] 2020-02-26 08:37
I compared your settings to mine and there are no significant differences, so that's not the cause

**Comment by Sigma88** [comment] 2020-02-26 08:48
Also, I know you have previously dismissed the option, but since we are not making any progres...

Could you try moving the KSP folder to `C:\Games\KSP\` or something, see if that helps

I have mine in `C:\Games\KSP\`

**Comment by gordonfpanam** [comment] 2020-02-27 02:20
For these next tests I ran them from a USB 3 device formatted using exFAT, so no permissions issues to contend with.

I have access to a couple of potatoes. First, a Lenovo X1 Carbon with Integrated graphics:

![screenshot4](https://user-images.githubusercontent.com/25485283/75406071-22012480-58d5-11ea-92eb-4db8edb24c81.png)

[Logs-Kopernicus-LenovoCarbonX1.zip](https://github.com/Kopernicus/Kopernicus/files/4259140/Logs-Kopernicus-LenovoCarbonX1.zip)

And an HP Envy from three years ago, with Radeon discrete graphics:

![screenshot5](https://user-images.githubusercontent.com/25485283/75406142-51179600-58d5-11ea-8379-5567d54d042a.png)

[Logs-Kopernicus-HP-EnvyTS15.zip](https://github.com/Kopernicus/Kopernicus/files/4259146/Logs-Kopernicus-HP-EnvyTS15.zip)

I'm getting the same result on both of these as well, with different processors and graphics.

**Comment by Sigma88** [comment] 2020-02-27 11:17
To launch KSP do you use `KSP_x64.exe` or `Launcher.exe` ?

**Comment by Sigma88** [comment] 2020-02-27 15:00
If you tell me how to contact you directly I will send you a dev version to test if the issue is still there in the latest release

**Comment by gordonfpanam** [comment] 2020-02-27 23:20
When I launch KSP I use the ksp_x64.exe and skip the launcher.

Thanks for considering letting me check out the dev version! I can be reached at gordonf@pan-am.ca or on Discord as gordonf4ksp. I'm on the Kopernicus server.

**Comment by gordonfpanam** [comment] 2020-02-28 15:31
So far the test version is working much better. I'll make sure to test with the potatoes as well.

**Comment by xhc12345** [comment] 2020-04-11 05:36
[Hello there! I am experiencing the exact same issue. I have no planet mods installed and yet I am getting the same issue on 1.8.1. However, I do have scatterer installed.

I don't think it's my setup's problem, but here's my spec:
CPU: AMD Ryzen 5 1600x @3.9GHz
RAM: 2x8GB DDR4, 2933MHz
GPU: Nvidia GTX 1060 6GB  @1866MHz

I initially discovered it when I cheat my rover to Eve, Laythe, and Duna for testing. Duna was the only planet of the three without missing tiles. Kerbin has no tiles either, strangely. I usually launch KSP_x64.exe directly without the Launcher.exe, but Launcher seems to be no fixing the issue either.

I downloaded Kopernicus 1.8.1.1 on February 24th, the day after you discovered the problem

Later I tested your save file "Bloody Hell", and the same problem persists. 
By pure chance, I reentered your Ariel in the same area.
![屏幕截图(323)](https://user-images.githubusercontent.com/63487829/79036222-d60bf580-7b8b-11ea-90df-02fa7160fcdf.png)
That's right. **THE EXACT SAME NUMBER, PATTERN, AND LOCATION FOR THE MISSING TILES AS THE SCREENSHOT YOU POSTED**
![屏幕截图(324)](https://user-images.githubusercontent.com/63487829/79036241-f936a500-7b8b-11ea-9586-5f5d256d8327.png)
This is perhaps suggesting the case is not an individual case, but instead something wrong with the code.
Flying further towards the missing tiles only cause more tiles to vaporize.
![屏幕截图(325)](https://user-images.githubusercontent.com/63487829/79036272-55012e00-7b8c-11ea-9be0-c08607fbb417.png)
![屏幕截图(319)](https://user-images.githubusercontent.com/63487829/79036277-5e8a9600-7b8c-11ea-9c90-99df5d191e33.png)

I would love to know how the dev version works out for you!

**Comment by Sigma88** [comment] 2020-04-11 11:03
The issue has been solved in the latest dev version.

If you know how to compile c# you can just compile the master branch (or the PanelsFix2 branch)

I don't usually give out dev versions. You could ask thomas for one.

**Comment by Rudzio20** [comment] 2020-05-01 07:11
Hey, 
maybe you could help me, i dont know what a dev version is or c# , but i have the same problem like gordonfpanam in 1.8.1 with kopernicus. Is there a fix out right now?

Thank you for the support!

**Comment by R-T-B** [comment] 2020-09-11 01:51
Closing this old issue as part of a broader cleanup.  If you still have issues reopen a new issue.  It should be fixed in the latest releases.

**Closed by R-T-B** 2020-09-11 01:51 UTC
