### ISSUE TITLE
out of date 

### ISSUE THREAD

**Issue by ugenekrabs** [Kopernicus/Kopernicus#298] opened 2018-07-17 19:51 UTC
every time i start up ksp it syas that im not useing the right version of ksp or kopernicus i hvae the latest version of both dont know what im doing wrong

**Comment by DeltaDizzy** [comment] 2018-07-17 19:55
This issue should help you a lot with your question.
[https://github.com/Kopernicus/Kopernicus/issues/296](https://github.com/Kopernicus/Kopernicus/issues/296)

**Comment by Sigma88** [comment] 2018-07-18 20:30
closed because it is a duplicate of issue 296

**Closed by Sigma88** 2018-07-18 20:30 UTC

**Comment by marr75** [comment] 2018-07-27 05:15
@TangChr I'm not having any problems on 1.4.5 and had no problems on 1.4.4

**Comment by TangChr** [comment] 2018-07-27 10:01
@marr75 I have just read the README more carefully (maybe I should do that in the future).

The Compiling-section states, that I have to copy some files from the Managed-directory. I can't find KSPUtil.dll and ModularFlightIntegrator.dll in this directory.

I noticed that the other assemblies are included as NuGet packages.

Now if I compile a Release, I still get a warning, and Kopernicus doesn't load.

I'm using KSP 1.4.5

**Comment by marr75** [comment] 2018-07-27 22:58
You would need to check out tag release-1.4.3-2 and compile it with `DEBUG` defined or `CompatibilityChecker.IsCompatible` overridden. They only release version locked binaries and so it follows that the source builds version locked binaries by default.
