### ISSUE TITLE
Odd shadows on vessels at certain angles

### ISSUE THREAD

**Issue by Machine-Maker** [Kopernicus/Kopernicus#523] opened 2022-05-07 00:24 UTC
I narrowed down this shadow issue I was having to Kopernicus (which I originally asked about [on the forums](https://forum.kerbalspaceprogram.com/index.php?/topic/206976-weird-shadow-effects-when-camera-is-at-certain-angles/)). The video shows several odd shadows when I pan around a vessel. Only installed mods are:
* OPM (tested w/o as well, and same thing happens)
* Community Terrain Texture Pack (dependency of Kopernicus)
* HyperEdit (for moving vessels easily)
* ModularFlightIntegreator (dependency of Kopernicus)
* ModuleManager (dependency of Kopernicus)
* Kopernicus

https://youtu.be/x43HosFaGOg

Here is the log as well.
[KSP.log](https://github.com/Kopernicus/Kopernicus/files/8644105/KSP.log)

**Comment by Machine-Maker** [comment] 2022-05-07 00:44
Just a quick note, adding scatterer (default everything) seems to get rid of the odd shadows, but I feel like that shouldn't be a requirement.

**Comment by R-T-B** [comment] 2022-05-07 17:00
Just FYI, this is a known issue and is high priority for a fix, we just have no idea why it happens unfortunately.  Right now scatterer is the only work around known.

Closing as duplicate of #501 (yes the bug is that old unfortunately).

**Closed** 2022-05-07 17:01 UTC
Labels: duplicate

**Comment by Machine-Maker** [comment] 2022-05-08 04:21
Ok thanks, saw that issue, wasn't sure if it was the same thing and it was kinda stale. Glad its a high prio.
