### ISSUE TITLE
Terrain scatter is broken in 1.3.0-4

### ISSUE THREAD

**Issue by Avera9eJoe** [Kopernicus/Kopernicus#193] opened 2017-07-07 17:58 UTC
Title. Moving terrain scatter configs from 1.2.2 to the 1.3.0-4 release of Kopernicus causes all custom terrain scatters to not show up, and prevents even the stock scatters from showing up.

**Comment by StollD** [comment] 2017-07-07 18:00
Duplicate of #189

**Closed by StollD** 2017-07-07 18:00 UTC
