### ISSUE TITLE
Orbits Shifting 

### ISSUE THREAD

**Issue by RyderReed15** [Kopernicus/Kopernicus#162] opened 2017-02-21 00:03 UTC
I'm not entirely sure if this is a Kopernicus bug, but when I close out of ksp and reopen it all of my orbits shift slightly. If I set two objects to the same exact orbit with cheats the shift exactly the same, but in different places. I am assuming this is a problem with caching the location of the planets in their orbits at a slightly different time than the orbits of flights are caches and so when they are reloaded the flights are slightly offset from the planet. The only mod im using that has anything to do with planets is Kerbol StarSystrm

**Comment by RyderReed15** [comment] 2017-02-21 00:04
Forgot to add that this is the most recent version and has been occurring in previous ones aswell

**Comment by Sigma88** [comment] 2017-02-21 09:15
Kerbol StarSystem is a pretty bad mod that has a lot of issues in how it interacts with kopernicus.

I would advise you to try and reproduce the bug on a stock install with only Kopernicus/MFI installed

if you still see the bug then provide us with the files described [here](http://forum.kerbalspaceprogram.com/index.php?/topic/140580-122-kopernicus-release-3-february-2/&page=27#comment-2793409)

also, try do the same thing on a stock install without any mods. it might be that this is a stock bug. if you don't see the bug on stock KSP but you see it in stock KSP + Kopernicus then we will need to look at what causes this in the kopernicus code

thanks for your report

**Comment by RyderReed15** [comment] 2017-02-21 20:03
Upon further inspection this is in fact a default ksp bug. When time-warping but not on rails the orbits shift but go back to normal withing a 1-3 meter margin. however when the object in orbit is not loaded they don't go back. Sorry for wasting your time, and i agree with you KSS is terrible, but it is the only mod that fits my need no matter how bad it is. In some cases on Minmus you can actually land below 0m and the entire planet unloads.

**Comment by Sigma88** [comment] 2017-02-22 10:03
I guess we can close this issue since it has nothing to do with kopernicus

@StollD feel free :)

**Closed** 2017-02-22 15:13 UTC
