### ISSUE TITLE
FAR incompability on DX11

### ISSUE THREAD

**Issue by agustincaniglia** [Kopernicus/Kopernicus#247] opened 2017-11-22 20:44 UTC
forcing ksp tu run on dx11 (something that I really want in order for the new mod TexturesUnlimited to work properly) messes the SVT textures. BUT, not without Ferram's FAR installed! If Far is not installed then DX11 and SVT work fine. It's just that FAR messes up something and that's when SVT textures fail to work properly. Here is an image of what breaks when it does: https://www.dropbox.com/s/gjlgdj5q8kqx9lh/KSP.bmp?dl=0
Maybe It is better fixed on FAR, so I'll let them know too.
Please tell me if can anybody find a fix, because I know nothing, just made trial and error a thousand times to figure out what mods were causing these glitches and now I know.
EDIT: ModularFlightIntegrator I think is what's causing the problem, this installed without FAR is enough for the texture glitches

**Comment by Sigma88** [comment] 2017-12-04 08:24
what exactly is SVT?

**Comment by DeltaDizzy** [comment] 2017-12-04 08:27
Stock Visual Terrain

**Comment by Sigma88** [comment] 2017-12-04 08:33
then please report this issue to the SVT developers

they know their mod better than us (or you) and they will determine if kopernicus is the cause of the bug.

if that is the case, they will take care of contacting us to get the issue sorted out.


keep in mind that this is always a good suggestion when reporting a bug.

unless this behaviour shows up on a simple Stock install + Kopernicus and dependancies + forced DX11, this bug should be reported to the developers of the mod causing the bug, so in this case SVT

this will help getting the issue sorted out more quickly because the devs of SVT have a much better knowledge of what parts of Kopernicus their mod uses and they can very easily determine which feature of their mod is causing your issue

closing this for now, if you have any more questions feel free to ask on the [forum thread](https://forum.kerbalspaceprogram.com/index.php?/topic/140580-0/), [discord](https://discord.me/kopernicus) or down here

**Closed by Sigma88** 2017-12-04 08:33 UTC
